---
layout: post
title: Install and set up RStudio server
status: wait
published: false
---

## Install Virtual Machine

## Install Ubuntu server on Virtual Machine

## Install R on Ubuntu server

* Add deb https://cloud.r-project.org/bin/linux/ubuntu xenial/ in /etc/apt/sources.list file
* Run
```
sudo apt-get update
sudo apt-get install r-base
sudo apt-get install r-base-dev
```

## Install RStudio server
```
sudo apt-get install gdebi-core
wget https://download2.rstudio.org/rstudio-server-0.99.903-amd64.deb
sudo gdebi rstudio-server-0.99.903-amd64.deb
```

## Update MacPorts (https://trac.macports.org/wiki/Migration)
* Re-install MacPorts: https://www.macports.org/install.php 
* Re-install ports:
    + Save the list of installed ports: port -qv installed > myports.txt
    + Uninstall all installed ports: sudo port -f uninstall installed
    + Clean any partially-completed builds: sudo rm -rf /opt/local/var/macports/build/*
    + Download and execute the restore_ports script: 
    ```
    curl -O https://svn.macports.org/repository/macports/contrib/restore_ports/restore_ports.tcl
chmod +x restore_ports.tcl
sudo ./restore_ports.tcl myports.txt
    ```

## Install git
```
sudo port install git
```

## Install other requirements from MacPorts
```
sudo port install cmake apache-ant
```

## Get RStudio Server source code
```
git clone https://github.com/rstudio/rstudio.git
```

## Install dependencies provided by RStudio
```
cd rstudio/dependencies/osx/
sudo ./install-dependencies-osx
cd ../.. # Go back to rstudio directory
```

## Build RStudio Server
```
mkdir build
cd build
cmake -DRSTUDIO_TARGET=Server -DCMAKE_BUILD_TYPE=Release ..
sudo make install
```

## Configure the Server to Start at Boot
Create file /Library/LaunchDaemons/org.rstudio.launchd.rserver.plist with
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"
        "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>Label</key>
        <string>com.rstudio.launchd.rstudio</string>
        <key>ProgramArguments</key>
        <array>
                <string>/usr/local/lib/rstudio-server/bin/rserver</string>
        </array>
        <key>RunAtLoad</key>
        <true/>
</dict>
</plist>
```

## Start the server
sudo defaults write /Library/LaunchDaemons/org.rstudio.launchd.rserver.plist Disabled -bool false
sudo launchctl load /Library/LaunchDaemons/org.rstudio.launchd.rserver.plist

## Test the server
At http://localhost:8787 

## Create /etc/rstudio/rserver.conf with
auth-minimum-user-id=100

## Create additional folders
sudo mkdir -p /var/run/rstudio-server
sudo mkdir -p /var/log/rstudio-server
sudo mkdir -p /var/lock/rstudio-server
sudo mkdir -p /var/lib/rstudio-server

## To add user
```
sudo cp /etc/pam.d/login /etc/pam.d/rstudio
```

## Check UID
```
dscl . -read /Users/Alice UniqueID
dscl . -change /Users/Alice UniqueID 501 1234
```

